// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/chord.proto

package chord

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Objetos del Chord
// Nodo que contiene una ID y una direccion IP.
type Node struct {
	ID                   []byte   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	IP                   string   `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *Node) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *Node) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

// Las request que pasan un nodo
type SetPredecessorRequest struct {
	Predecessor          *Node    `protobuf:"bytes,1,opt,name=predecessor,proto3" json:"predecessor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPredecessorRequest) Reset()         { *m = SetPredecessorRequest{} }
func (m *SetPredecessorRequest) String() string { return proto.CompactTextString(m) }
func (*SetPredecessorRequest) ProtoMessage()    {}
func (*SetPredecessorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{1}
}

func (m *SetPredecessorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPredecessorRequest.Unmarshal(m, b)
}
func (m *SetPredecessorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPredecessorRequest.Marshal(b, m, deterministic)
}
func (m *SetPredecessorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPredecessorRequest.Merge(m, src)
}
func (m *SetPredecessorRequest) XXX_Size() int {
	return xxx_messageInfo_SetPredecessorRequest.Size(m)
}
func (m *SetPredecessorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPredecessorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPredecessorRequest proto.InternalMessageInfo

func (m *SetPredecessorRequest) GetPredecessor() *Node {
	if m != nil {
		return m.Predecessor
	}
	return nil
}

type SetSuccessorRequest struct {
	Successor            *Node    `protobuf:"bytes,1,opt,name=successor,proto3" json:"successor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSuccessorRequest) Reset()         { *m = SetSuccessorRequest{} }
func (m *SetSuccessorRequest) String() string { return proto.CompactTextString(m) }
func (*SetSuccessorRequest) ProtoMessage()    {}
func (*SetSuccessorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{2}
}

func (m *SetSuccessorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSuccessorRequest.Unmarshal(m, b)
}
func (m *SetSuccessorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSuccessorRequest.Marshal(b, m, deterministic)
}
func (m *SetSuccessorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSuccessorRequest.Merge(m, src)
}
func (m *SetSuccessorRequest) XXX_Size() int {
	return xxx_messageInfo_SetSuccessorRequest.Size(m)
}
func (m *SetSuccessorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSuccessorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetSuccessorRequest proto.InternalMessageInfo

func (m *SetSuccessorRequest) GetSuccessor() *Node {
	if m != nil {
		return m.Successor
	}
	return nil
}

type NotifyRequest struct {
	Notify               *Node    `protobuf:"bytes,1,opt,name=notify,proto3" json:"notify,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyRequest) Reset()         { *m = NotifyRequest{} }
func (m *NotifyRequest) String() string { return proto.CompactTextString(m) }
func (*NotifyRequest) ProtoMessage()    {}
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{3}
}

func (m *NotifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyRequest.Unmarshal(m, b)
}
func (m *NotifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyRequest.Marshal(b, m, deterministic)
}
func (m *NotifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyRequest.Merge(m, src)
}
func (m *NotifyRequest) XXX_Size() int {
	return xxx_messageInfo_NotifyRequest.Size(m)
}
func (m *NotifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyRequest proto.InternalMessageInfo

func (m *NotifyRequest) GetNotify() *Node {
	if m != nil {
		return m.Notify
	}
	return nil
}

//Las respuestas que devuelven un nodo
type GetPredecessorResponse struct {
	Predecessor          *Node    `protobuf:"bytes,1,opt,name=predecessor,proto3" json:"predecessor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPredecessorResponse) Reset()         { *m = GetPredecessorResponse{} }
func (m *GetPredecessorResponse) String() string { return proto.CompactTextString(m) }
func (*GetPredecessorResponse) ProtoMessage()    {}
func (*GetPredecessorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{4}
}

func (m *GetPredecessorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPredecessorResponse.Unmarshal(m, b)
}
func (m *GetPredecessorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPredecessorResponse.Marshal(b, m, deterministic)
}
func (m *GetPredecessorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPredecessorResponse.Merge(m, src)
}
func (m *GetPredecessorResponse) XXX_Size() int {
	return xxx_messageInfo_GetPredecessorResponse.Size(m)
}
func (m *GetPredecessorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPredecessorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPredecessorResponse proto.InternalMessageInfo

func (m *GetPredecessorResponse) GetPredecessor() *Node {
	if m != nil {
		return m.Predecessor
	}
	return nil
}

type GetSuccessorResponse struct {
	Successor            *Node    `protobuf:"bytes,1,opt,name=successor,proto3" json:"successor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSuccessorResponse) Reset()         { *m = GetSuccessorResponse{} }
func (m *GetSuccessorResponse) String() string { return proto.CompactTextString(m) }
func (*GetSuccessorResponse) ProtoMessage()    {}
func (*GetSuccessorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{5}
}

func (m *GetSuccessorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSuccessorResponse.Unmarshal(m, b)
}
func (m *GetSuccessorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSuccessorResponse.Marshal(b, m, deterministic)
}
func (m *GetSuccessorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSuccessorResponse.Merge(m, src)
}
func (m *GetSuccessorResponse) XXX_Size() int {
	return xxx_messageInfo_GetSuccessorResponse.Size(m)
}
func (m *GetSuccessorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSuccessorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSuccessorResponse proto.InternalMessageInfo

func (m *GetSuccessorResponse) GetSuccessor() *Node {
	if m != nil {
		return m.Successor
	}
	return nil
}

type FindSuccesorResponse struct {
	Succesor             *Node    `protobuf:"bytes,1,opt,name=succesor,proto3" json:"succesor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindSuccesorResponse) Reset()         { *m = FindSuccesorResponse{} }
func (m *FindSuccesorResponse) String() string { return proto.CompactTextString(m) }
func (*FindSuccesorResponse) ProtoMessage()    {}
func (*FindSuccesorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{6}
}

func (m *FindSuccesorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindSuccesorResponse.Unmarshal(m, b)
}
func (m *FindSuccesorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindSuccesorResponse.Marshal(b, m, deterministic)
}
func (m *FindSuccesorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindSuccesorResponse.Merge(m, src)
}
func (m *FindSuccesorResponse) XXX_Size() int {
	return xxx_messageInfo_FindSuccesorResponse.Size(m)
}
func (m *FindSuccesorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindSuccesorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindSuccesorResponse proto.InternalMessageInfo

func (m *FindSuccesorResponse) GetSuccesor() *Node {
	if m != nil {
		return m.Succesor
	}
	return nil
}

// Otras Request
type FindSuccesorRequest struct {
	ID                   []byte   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindSuccesorRequest) Reset()         { *m = FindSuccesorRequest{} }
func (m *FindSuccesorRequest) String() string { return proto.CompactTextString(m) }
func (*FindSuccesorRequest) ProtoMessage()    {}
func (*FindSuccesorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{7}
}

func (m *FindSuccesorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindSuccesorRequest.Unmarshal(m, b)
}
func (m *FindSuccesorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindSuccesorRequest.Marshal(b, m, deterministic)
}
func (m *FindSuccesorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindSuccesorRequest.Merge(m, src)
}
func (m *FindSuccesorRequest) XXX_Size() int {
	return xxx_messageInfo_FindSuccesorRequest.Size(m)
}
func (m *FindSuccesorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindSuccesorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindSuccesorRequest proto.InternalMessageInfo

func (m *FindSuccesorRequest) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

// Las Request vacias
type GetPredecessorRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPredecessorRequest) Reset()         { *m = GetPredecessorRequest{} }
func (m *GetPredecessorRequest) String() string { return proto.CompactTextString(m) }
func (*GetPredecessorRequest) ProtoMessage()    {}
func (*GetPredecessorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{8}
}

func (m *GetPredecessorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPredecessorRequest.Unmarshal(m, b)
}
func (m *GetPredecessorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPredecessorRequest.Marshal(b, m, deterministic)
}
func (m *GetPredecessorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPredecessorRequest.Merge(m, src)
}
func (m *GetPredecessorRequest) XXX_Size() int {
	return xxx_messageInfo_GetPredecessorRequest.Size(m)
}
func (m *GetPredecessorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPredecessorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPredecessorRequest proto.InternalMessageInfo

type GetSuccessorRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSuccessorRequest) Reset()         { *m = GetSuccessorRequest{} }
func (m *GetSuccessorRequest) String() string { return proto.CompactTextString(m) }
func (*GetSuccessorRequest) ProtoMessage()    {}
func (*GetSuccessorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{9}
}

func (m *GetSuccessorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSuccessorRequest.Unmarshal(m, b)
}
func (m *GetSuccessorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSuccessorRequest.Marshal(b, m, deterministic)
}
func (m *GetSuccessorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSuccessorRequest.Merge(m, src)
}
func (m *GetSuccessorRequest) XXX_Size() int {
	return xxx_messageInfo_GetSuccessorRequest.Size(m)
}
func (m *GetSuccessorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSuccessorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSuccessorRequest proto.InternalMessageInfo

type CheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckRequest) Reset()         { *m = CheckRequest{} }
func (m *CheckRequest) String() string { return proto.CompactTextString(m) }
func (*CheckRequest) ProtoMessage()    {}
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{10}
}

func (m *CheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRequest.Unmarshal(m, b)
}
func (m *CheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRequest.Marshal(b, m, deterministic)
}
func (m *CheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRequest.Merge(m, src)
}
func (m *CheckRequest) XXX_Size() int {
	return xxx_messageInfo_CheckRequest.Size(m)
}
func (m *CheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRequest proto.InternalMessageInfo

type PartitionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartitionRequest) Reset()         { *m = PartitionRequest{} }
func (m *PartitionRequest) String() string { return proto.CompactTextString(m) }
func (*PartitionRequest) ProtoMessage()    {}
func (*PartitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{11}
}

func (m *PartitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionRequest.Unmarshal(m, b)
}
func (m *PartitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionRequest.Marshal(b, m, deterministic)
}
func (m *PartitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionRequest.Merge(m, src)
}
func (m *PartitionRequest) XXX_Size() int {
	return xxx_messageInfo_PartitionRequest.Size(m)
}
func (m *PartitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionRequest proto.InternalMessageInfo

type ExtendResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtendResponse) Reset()         { *m = ExtendResponse{} }
func (m *ExtendResponse) String() string { return proto.CompactTextString(m) }
func (*ExtendResponse) ProtoMessage()    {}
func (*ExtendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{12}
}

func (m *ExtendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtendResponse.Unmarshal(m, b)
}
func (m *ExtendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtendResponse.Marshal(b, m, deterministic)
}
func (m *ExtendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtendResponse.Merge(m, src)
}
func (m *ExtendResponse) XXX_Size() int {
	return xxx_messageInfo_ExtendResponse.Size(m)
}
func (m *ExtendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExtendResponse proto.InternalMessageInfo

// Las respuestas vacias
type SetPredecessorResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPredecessorResponse) Reset()         { *m = SetPredecessorResponse{} }
func (m *SetPredecessorResponse) String() string { return proto.CompactTextString(m) }
func (*SetPredecessorResponse) ProtoMessage()    {}
func (*SetPredecessorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{13}
}

func (m *SetPredecessorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPredecessorResponse.Unmarshal(m, b)
}
func (m *SetPredecessorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPredecessorResponse.Marshal(b, m, deterministic)
}
func (m *SetPredecessorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPredecessorResponse.Merge(m, src)
}
func (m *SetPredecessorResponse) XXX_Size() int {
	return xxx_messageInfo_SetPredecessorResponse.Size(m)
}
func (m *SetPredecessorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPredecessorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetPredecessorResponse proto.InternalMessageInfo

type SetSuccessorResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSuccessorResponse) Reset()         { *m = SetSuccessorResponse{} }
func (m *SetSuccessorResponse) String() string { return proto.CompactTextString(m) }
func (*SetSuccessorResponse) ProtoMessage()    {}
func (*SetSuccessorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{14}
}

func (m *SetSuccessorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSuccessorResponse.Unmarshal(m, b)
}
func (m *SetSuccessorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSuccessorResponse.Marshal(b, m, deterministic)
}
func (m *SetSuccessorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSuccessorResponse.Merge(m, src)
}
func (m *SetSuccessorResponse) XXX_Size() int {
	return xxx_messageInfo_SetSuccessorResponse.Size(m)
}
func (m *SetSuccessorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSuccessorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetSuccessorResponse proto.InternalMessageInfo

type NotifyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyResponse) Reset()         { *m = NotifyResponse{} }
func (m *NotifyResponse) String() string { return proto.CompactTextString(m) }
func (*NotifyResponse) ProtoMessage()    {}
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{15}
}

func (m *NotifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyResponse.Unmarshal(m, b)
}
func (m *NotifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyResponse.Marshal(b, m, deterministic)
}
func (m *NotifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyResponse.Merge(m, src)
}
func (m *NotifyResponse) XXX_Size() int {
	return xxx_messageInfo_NotifyResponse.Size(m)
}
func (m *NotifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyResponse proto.InternalMessageInfo

type CheckResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckResponse) Reset()         { *m = CheckResponse{} }
func (m *CheckResponse) String() string { return proto.CompactTextString(m) }
func (*CheckResponse) ProtoMessage()    {}
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{16}
}

func (m *CheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResponse.Unmarshal(m, b)
}
func (m *CheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResponse.Marshal(b, m, deterministic)
}
func (m *CheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResponse.Merge(m, src)
}
func (m *CheckResponse) XXX_Size() int {
	return xxx_messageInfo_CheckResponse.Size(m)
}
func (m *CheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResponse proto.InternalMessageInfo

type DiscardResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscardResponse) Reset()         { *m = DiscardResponse{} }
func (m *DiscardResponse) String() string { return proto.CompactTextString(m) }
func (*DiscardResponse) ProtoMessage()    {}
func (*DiscardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{17}
}

func (m *DiscardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscardResponse.Unmarshal(m, b)
}
func (m *DiscardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscardResponse.Marshal(b, m, deterministic)
}
func (m *DiscardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscardResponse.Merge(m, src)
}
func (m *DiscardResponse) XXX_Size() int {
	return xxx_messageInfo_DiscardResponse.Size(m)
}
func (m *DiscardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiscardResponse proto.InternalMessageInfo

type SetRequest struct {
	Ident                string   `protobuf:"bytes,1,opt,name=ident,proto3" json:"ident,omitempty"`
	File                 []byte   `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Replication          bool     `protobuf:"varint,3,opt,name=replication,proto3" json:"replication,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{18}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func (m *SetRequest) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *SetRequest) GetReplication() bool {
	if m != nil {
		return m.Replication
	}
	return false
}

type SetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResponse) Reset()         { *m = SetResponse{} }
func (m *SetResponse) String() string { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()    {}
func (*SetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{19}
}

func (m *SetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResponse.Unmarshal(m, b)
}
func (m *SetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResponse.Marshal(b, m, deterministic)
}
func (m *SetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResponse.Merge(m, src)
}
func (m *SetResponse) XXX_Size() int {
	return xxx_messageInfo_SetResponse.Size(m)
}
func (m *SetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetResponse proto.InternalMessageInfo

type GetRequest struct {
	Ident                string   `protobuf:"bytes,1,opt,name=ident,proto3" json:"ident,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{20}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

type GetResponse struct {
	ResponseFile         []byte   `protobuf:"bytes,1,opt,name=responseFile,proto3" json:"responseFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{21}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetResponseFile() []byte {
	if m != nil {
		return m.ResponseFile
	}
	return nil
}

type DeleteRequest struct {
	Ident                string   `protobuf:"bytes,1,opt,name=ident,proto3" json:"ident,omitempty"`
	Replication          bool     `protobuf:"varint,2,opt,name=replication,proto3" json:"replication,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{22}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func (m *DeleteRequest) GetReplication() bool {
	if m != nil {
		return m.Replication
	}
	return false
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{23}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

type DeleteElemnRequest struct {
	Ident                string   `protobuf:"bytes,1,opt,name=ident,proto3" json:"ident,omitempty"`
	RemoveFile           []string `protobuf:"bytes,2,rep,name=removeFile,proto3" json:"removeFile,omitempty"`
	Replication          bool     `protobuf:"varint,3,opt,name=replication,proto3" json:"replication,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteElemnRequest) Reset()         { *m = DeleteElemnRequest{} }
func (m *DeleteElemnRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteElemnRequest) ProtoMessage()    {}
func (*DeleteElemnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{24}
}

func (m *DeleteElemnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteElemnRequest.Unmarshal(m, b)
}
func (m *DeleteElemnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteElemnRequest.Marshal(b, m, deterministic)
}
func (m *DeleteElemnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteElemnRequest.Merge(m, src)
}
func (m *DeleteElemnRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteElemnRequest.Size(m)
}
func (m *DeleteElemnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteElemnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteElemnRequest proto.InternalMessageInfo

func (m *DeleteElemnRequest) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func (m *DeleteElemnRequest) GetRemoveFile() []string {
	if m != nil {
		return m.RemoveFile
	}
	return nil
}

func (m *DeleteElemnRequest) GetReplication() bool {
	if m != nil {
		return m.Replication
	}
	return false
}

type DeleteElemnResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteElemnResponse) Reset()         { *m = DeleteElemnResponse{} }
func (m *DeleteElemnResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteElemnResponse) ProtoMessage()    {}
func (*DeleteElemnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{25}
}

func (m *DeleteElemnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteElemnResponse.Unmarshal(m, b)
}
func (m *DeleteElemnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteElemnResponse.Marshal(b, m, deterministic)
}
func (m *DeleteElemnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteElemnResponse.Merge(m, src)
}
func (m *DeleteElemnResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteElemnResponse.Size(m)
}
func (m *DeleteElemnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteElemnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteElemnResponse proto.InternalMessageInfo

func (m *DeleteElemnResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type SetElemRequest struct {
	Ident                string   `protobuf:"bytes,1,opt,name=ident,proto3" json:"ident,omitempty"`
	SetFile              []string `protobuf:"bytes,2,rep,name=setFile,proto3" json:"setFile,omitempty"`
	Replication          bool     `protobuf:"varint,3,opt,name=replication,proto3" json:"replication,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetElemRequest) Reset()         { *m = SetElemRequest{} }
func (m *SetElemRequest) String() string { return proto.CompactTextString(m) }
func (*SetElemRequest) ProtoMessage()    {}
func (*SetElemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{26}
}

func (m *SetElemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetElemRequest.Unmarshal(m, b)
}
func (m *SetElemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetElemRequest.Marshal(b, m, deterministic)
}
func (m *SetElemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetElemRequest.Merge(m, src)
}
func (m *SetElemRequest) XXX_Size() int {
	return xxx_messageInfo_SetElemRequest.Size(m)
}
func (m *SetElemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetElemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetElemRequest proto.InternalMessageInfo

func (m *SetElemRequest) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func (m *SetElemRequest) GetSetFile() []string {
	if m != nil {
		return m.SetFile
	}
	return nil
}

func (m *SetElemRequest) GetReplication() bool {
	if m != nil {
		return m.Replication
	}
	return false
}

type SetElemResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetElemResponse) Reset()         { *m = SetElemResponse{} }
func (m *SetElemResponse) String() string { return proto.CompactTextString(m) }
func (*SetElemResponse) ProtoMessage()    {}
func (*SetElemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{27}
}

func (m *SetElemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetElemResponse.Unmarshal(m, b)
}
func (m *SetElemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetElemResponse.Marshal(b, m, deterministic)
}
func (m *SetElemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetElemResponse.Merge(m, src)
}
func (m *SetElemResponse) XXX_Size() int {
	return xxx_messageInfo_SetElemResponse.Size(m)
}
func (m *SetElemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetElemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetElemResponse proto.InternalMessageInfo

func (m *SetElemResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

// PartitionResponse contains the contains the <key, value> pairs to return.
type PartitionResponse struct {
	InFiles              map[string][]byte `protobuf:"bytes,1,rep,name=inFiles,proto3" json:"inFiles,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	OutFiles             map[string][]byte `protobuf:"bytes,2,rep,name=outFiles,proto3" json:"outFiles,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PartitionResponse) Reset()         { *m = PartitionResponse{} }
func (m *PartitionResponse) String() string { return proto.CompactTextString(m) }
func (*PartitionResponse) ProtoMessage()    {}
func (*PartitionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{28}
}

func (m *PartitionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionResponse.Unmarshal(m, b)
}
func (m *PartitionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionResponse.Marshal(b, m, deterministic)
}
func (m *PartitionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionResponse.Merge(m, src)
}
func (m *PartitionResponse) XXX_Size() int {
	return xxx_messageInfo_PartitionResponse.Size(m)
}
func (m *PartitionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionResponse proto.InternalMessageInfo

func (m *PartitionResponse) GetInFiles() map[string][]byte {
	if m != nil {
		return m.InFiles
	}
	return nil
}

func (m *PartitionResponse) GetOutFiles() map[string][]byte {
	if m != nil {
		return m.OutFiles
	}
	return nil
}

type ExtendRequest struct {
	ExtendFiles          map[string][]byte `protobuf:"bytes,1,rep,name=extendFiles,proto3" json:"extendFiles,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ExtendRequest) Reset()         { *m = ExtendRequest{} }
func (m *ExtendRequest) String() string { return proto.CompactTextString(m) }
func (*ExtendRequest) ProtoMessage()    {}
func (*ExtendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{29}
}

func (m *ExtendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtendRequest.Unmarshal(m, b)
}
func (m *ExtendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtendRequest.Marshal(b, m, deterministic)
}
func (m *ExtendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtendRequest.Merge(m, src)
}
func (m *ExtendRequest) XXX_Size() int {
	return xxx_messageInfo_ExtendRequest.Size(m)
}
func (m *ExtendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExtendRequest proto.InternalMessageInfo

func (m *ExtendRequest) GetExtendFiles() map[string][]byte {
	if m != nil {
		return m.ExtendFiles
	}
	return nil
}

type DiscardRequest struct {
	DiscardFiles         []string `protobuf:"bytes,1,rep,name=discardFiles,proto3" json:"discardFiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscardRequest) Reset()         { *m = DiscardRequest{} }
func (m *DiscardRequest) String() string { return proto.CompactTextString(m) }
func (*DiscardRequest) ProtoMessage()    {}
func (*DiscardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a6d8fd300af2d7, []int{30}
}

func (m *DiscardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscardRequest.Unmarshal(m, b)
}
func (m *DiscardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscardRequest.Marshal(b, m, deterministic)
}
func (m *DiscardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscardRequest.Merge(m, src)
}
func (m *DiscardRequest) XXX_Size() int {
	return xxx_messageInfo_DiscardRequest.Size(m)
}
func (m *DiscardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiscardRequest proto.InternalMessageInfo

func (m *DiscardRequest) GetDiscardFiles() []string {
	if m != nil {
		return m.DiscardFiles
	}
	return nil
}

func init() {
	proto.RegisterType((*Node)(nil), "chord.Node")
	proto.RegisterType((*SetPredecessorRequest)(nil), "chord.SetPredecessorRequest")
	proto.RegisterType((*SetSuccessorRequest)(nil), "chord.SetSuccessorRequest")
	proto.RegisterType((*NotifyRequest)(nil), "chord.NotifyRequest")
	proto.RegisterType((*GetPredecessorResponse)(nil), "chord.GetPredecessorResponse")
	proto.RegisterType((*GetSuccessorResponse)(nil), "chord.GetSuccessorResponse")
	proto.RegisterType((*FindSuccesorResponse)(nil), "chord.FindSuccesorResponse")
	proto.RegisterType((*FindSuccesorRequest)(nil), "chord.FindSuccesorRequest")
	proto.RegisterType((*GetPredecessorRequest)(nil), "chord.GetPredecessorRequest")
	proto.RegisterType((*GetSuccessorRequest)(nil), "chord.GetSuccessorRequest")
	proto.RegisterType((*CheckRequest)(nil), "chord.CheckRequest")
	proto.RegisterType((*PartitionRequest)(nil), "chord.PartitionRequest")
	proto.RegisterType((*ExtendResponse)(nil), "chord.ExtendResponse")
	proto.RegisterType((*SetPredecessorResponse)(nil), "chord.SetPredecessorResponse")
	proto.RegisterType((*SetSuccessorResponse)(nil), "chord.SetSuccessorResponse")
	proto.RegisterType((*NotifyResponse)(nil), "chord.NotifyResponse")
	proto.RegisterType((*CheckResponse)(nil), "chord.CheckResponse")
	proto.RegisterType((*DiscardResponse)(nil), "chord.DiscardResponse")
	proto.RegisterType((*SetRequest)(nil), "chord.SetRequest")
	proto.RegisterType((*SetResponse)(nil), "chord.SetResponse")
	proto.RegisterType((*GetRequest)(nil), "chord.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "chord.GetResponse")
	proto.RegisterType((*DeleteRequest)(nil), "chord.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "chord.DeleteResponse")
	proto.RegisterType((*DeleteElemnRequest)(nil), "chord.DeleteElemnRequest")
	proto.RegisterType((*DeleteElemnResponse)(nil), "chord.DeleteElemnResponse")
	proto.RegisterType((*SetElemRequest)(nil), "chord.SetElemRequest")
	proto.RegisterType((*SetElemResponse)(nil), "chord.SetElemResponse")
	proto.RegisterType((*PartitionResponse)(nil), "chord.PartitionResponse")
	proto.RegisterMapType((map[string][]byte)(nil), "chord.PartitionResponse.InFilesEntry")
	proto.RegisterMapType((map[string][]byte)(nil), "chord.PartitionResponse.OutFilesEntry")
	proto.RegisterType((*ExtendRequest)(nil), "chord.ExtendRequest")
	proto.RegisterMapType((map[string][]byte)(nil), "chord.ExtendRequest.ExtendFilesEntry")
	proto.RegisterType((*DiscardRequest)(nil), "chord.DiscardRequest")
}

func init() {
	proto.RegisterFile("proto/chord.proto", fileDescriptor_01a6d8fd300af2d7)
}

var fileDescriptor_01a6d8fd300af2d7 = []byte{
	// 867 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0x5d, 0x6f, 0xdb, 0x36,
	0x14, 0x85, 0xe5, 0x26, 0x8e, 0x8f, 0x6c, 0xc7, 0xa1, 0x9d, 0xd4, 0xd3, 0x3e, 0x60, 0x70, 0xe8,
	0x96, 0x01, 0xab, 0x87, 0x7a, 0x2d, 0x50, 0x64, 0x40, 0xbb, 0xb5, 0x4e, 0x34, 0x3f, 0xb4, 0x33,
	0xa4, 0x97, 0x61, 0x6f, 0xae, 0xcd, 0xa2, 0x42, 0x5c, 0xc9, 0x93, 0xe8, 0x62, 0xf9, 0x19, 0x7b,
	0xdb, 0xcf, 0xd8, 0x4f, 0x1c, 0x44, 0x52, 0x12, 0x29, 0xcb, 0x5e, 0xfc, 0x26, 0x1e, 0xde, 0x7b,
	0xee, 0xb9, 0xe4, 0xe5, 0xbd, 0xc2, 0xd9, 0x3a, 0x8e, 0x78, 0xf4, 0xc3, 0xe2, 0x43, 0x14, 0x2f,
	0x47, 0xe2, 0x9b, 0x1c, 0x89, 0x05, 0xbd, 0xc2, 0x83, 0xb7, 0xd1, 0x92, 0x91, 0x0e, 0xac, 0xe9,
	0x64, 0x50, 0x1b, 0xd6, 0x2e, 0x5b, 0x9e, 0x35, 0x9d, 0x88, 0xf5, 0x6c, 0x60, 0x0d, 0x6b, 0x97,
	0x4d, 0xcf, 0x9a, 0xce, 0x08, 0xc1, 0x83, 0x75, 0x14, 0xf3, 0x41, 0x5d, 0x20, 0xe2, 0x9b, 0xde,
	0xe0, 0xdc, 0x67, 0x7c, 0x16, 0xb3, 0x25, 0x5b, 0xb0, 0x24, 0x89, 0x62, 0x8f, 0xfd, 0xb9, 0x61,
	0x09, 0x27, 0x8f, 0x61, 0xaf, 0x0b, 0x54, 0xb0, 0xda, 0x63, 0x7b, 0x24, 0xc3, 0xa7, 0xe1, 0x3c,
	0x7d, 0x9f, 0xfe, 0x8c, 0x9e, 0xcf, 0xb8, 0xbf, 0x59, 0x98, 0x2c, 0xdf, 0xa1, 0x99, 0x64, 0x58,
	0x15, 0x47, 0xb1, 0x4b, 0x9f, 0xa2, 0xfd, 0x36, 0xe2, 0xc1, 0xfb, 0xbb, 0xcc, 0xf7, 0x6b, 0x1c,
	0x87, 0x02, 0xa8, 0x72, 0x54, 0x5b, 0xd4, 0xc5, 0x85, 0x5b, 0xd2, 0x9f, 0xac, 0xa3, 0x30, 0x61,
	0x87, 0x26, 0xf0, 0x0b, 0xfa, 0xae, 0x91, 0x80, 0xa2, 0x39, 0x20, 0x83, 0x97, 0xe8, 0xdf, 0x04,
	0xe1, 0x52, 0x72, 0x68, 0x14, 0xdf, 0xe2, 0x24, 0x51, 0x58, 0x15, 0x43, 0xbe, 0x49, 0x1f, 0xa1,
	0x67, 0x12, 0xc8, 0x83, 0x28, 0xdd, 0x2b, 0x7d, 0x88, 0x73, 0xb7, 0xea, 0xce, 0xe8, 0x39, 0x7a,
	0xee, 0xf6, 0x25, 0xd0, 0x0e, 0x5a, 0xaf, 0x3f, 0xb0, 0xc5, 0x6d, 0xb6, 0x26, 0xe8, 0xce, 0xe6,
	0x31, 0x0f, 0x78, 0x10, 0x85, 0x19, 0xd6, 0x45, 0xe7, 0xfa, 0x2f, 0xce, 0xc2, 0x65, 0xa6, 0x9a,
	0x0e, 0x70, 0xe1, 0x57, 0x9e, 0x2c, 0xbd, 0x40, 0xdf, 0xaf, 0x38, 0xaa, 0x94, 0x23, 0xbb, 0x41,
	0x85, 0x9c, 0xa2, 0xad, 0x22, 0x2b, 0xe0, 0x0c, 0xa7, 0x93, 0x20, 0x59, 0xcc, 0xe3, 0x22, 0xce,
	0xef, 0x80, 0xcf, 0x78, 0x96, 0x6b, 0x1f, 0x47, 0xc1, 0x92, 0x85, 0x5c, 0xa4, 0xdb, 0xf4, 0xe4,
	0x22, 0xad, 0xdc, 0xf7, 0xc1, 0x8a, 0x89, 0x5a, 0x6e, 0x79, 0xe2, 0x9b, 0x0c, 0x61, 0xc7, 0x6c,
	0xbd, 0x0a, 0x16, 0xf3, 0x34, 0x0f, 0x51, 0xd4, 0x27, 0x9e, 0x0e, 0xd1, 0x36, 0x6c, 0xc1, 0xac,
	0x02, 0x51, 0xc0, 0xfd, 0x9f, 0x40, 0xf4, 0x09, 0x6c, 0xb7, 0x70, 0x21, 0x14, 0xad, 0x58, 0x7d,
	0xdf, 0xa4, 0xf1, 0xe5, 0x1d, 0x18, 0x18, 0x75, 0xd1, 0x9e, 0xb0, 0x15, 0xe3, 0x6c, 0x7f, 0x0a,
	0x25, 0xb9, 0xd6, 0xb6, 0xdc, 0x2e, 0x3a, 0x19, 0x91, 0x52, 0xbc, 0x02, 0x91, 0xc8, 0xf5, 0x8a,
	0x7d, 0x0c, 0xf7, 0xf3, 0x7f, 0x05, 0xc4, 0xec, 0x63, 0xf4, 0x49, 0x0a, 0xb5, 0x86, 0xf5, 0xcb,
	0xa6, 0xa7, 0x21, 0xf7, 0x38, 0xae, 0x27, 0xe8, 0x19, 0xd1, 0xd4, 0x19, 0x38, 0x38, 0xc9, 0xf2,
	0x55, 0x11, 0xf3, 0x35, 0x7d, 0x87, 0x8e, 0xcf, 0x78, 0x6a, 0xbf, 0x5f, 0xdc, 0x00, 0x8d, 0x84,
	0x71, 0x4d, 0x59, 0xb6, 0xbc, 0x87, 0xac, 0xc7, 0x38, 0xcd, 0x63, 0xdc, 0x43, 0xd2, 0xdf, 0x16,
	0xce, 0xb4, 0xea, 0x56, 0x1e, 0x2f, 0xd1, 0x08, 0xc2, 0x34, 0x60, 0x32, 0xa8, 0x0d, 0xeb, 0x97,
	0xf6, 0xf8, 0x91, 0x7a, 0x81, 0x5b, 0xa6, 0xa3, 0xa9, 0xb4, 0xbb, 0x0e, 0x79, 0x7c, 0xe7, 0x65,
	0x5e, 0xe4, 0x15, 0x4e, 0xa2, 0x0d, 0x97, 0x0c, 0x96, 0x60, 0xf8, 0x66, 0x27, 0xc3, 0x6f, 0xca,
	0x50, 0x52, 0xe4, 0x7e, 0xce, 0x15, 0x5a, 0x3a, 0x39, 0xe9, 0xa2, 0x7e, 0xcb, 0xee, 0x54, 0x06,
	0xe9, 0x67, 0x7a, 0x7a, 0x9f, 0xe6, 0xab, 0x4d, 0x56, 0xe8, 0x72, 0x71, 0x65, 0x3d, 0xaf, 0x39,
	0x3f, 0xa1, 0x6d, 0xd0, 0x1e, 0xe2, 0x4c, 0xff, 0xa9, 0xa1, 0x9d, 0xbd, 0x6e, 0x79, 0x4d, 0x2e,
	0x6c, 0x26, 0x80, 0xaa, 0x33, 0x31, 0x4c, 0xd5, 0x4a, 0x4b, 0x48, 0xf7, 0x74, 0x5e, 0xa0, 0x5b,
	0x36, 0x38, 0x48, 0xda, 0x53, 0x74, 0xf2, 0x86, 0x20, 0xa5, 0x51, 0xb4, 0x96, 0x12, 0x29, 0xb4,
	0x35, 0x3d, 0x03, 0x1b, 0xff, 0xdb, 0xc0, 0xd1, 0xeb, 0x54, 0x2b, 0x79, 0x83, 0x8e, 0xd9, 0x0b,
	0xc9, 0x17, 0x2a, 0x8b, 0xca, 0x16, 0xe9, 0x7c, 0xb9, 0x63, 0x57, 0xd5, 0x89, 0x8b, 0x96, 0xde,
	0x41, 0x89, 0x53, 0x98, 0x97, 0xdb, 0xaa, 0xf3, 0x79, 0xe5, 0x9e, 0x22, 0x7a, 0x23, 0x5e, 0x46,
	0x95, 0x2e, 0x7f, 0xaf, 0x2e, 0x7f, 0xa7, 0x2e, 0xbf, 0x4a, 0x97, 0xbf, 0x47, 0x57, 0x55, 0x8f,
	0x26, 0xbf, 0xa2, 0x5d, 0x8c, 0x18, 0x9d, 0xa9, 0x62, 0xf0, 0xe4, 0x4c, 0x95, 0x53, 0xed, 0x19,
	0x8e, 0x65, 0xb7, 0x27, 0xfd, 0x7c, 0x9a, 0x69, 0xe3, 0xdb, 0x39, 0x2f, 0xa1, 0xca, 0x6d, 0x9c,
	0xde, 0x1c, 0x5b, 0xdc, 0x92, 0x9e, 0xda, 0xd7, 0x47, 0x93, 0xd3, 0x37, 0x41, 0xe5, 0xf3, 0x02,
	0xcd, 0xfc, 0x95, 0x91, 0x87, 0xdb, 0xef, 0x4e, 0xfa, 0x0e, 0x76, 0x3d, 0xc8, 0x54, 0xaa, 0x2c,
	0xd2, 0x5c, 0xaa, 0x51, 0xe2, 0xb9, 0x54, 0x73, 0x02, 0x92, 0xe7, 0x68, 0xa8, 0xda, 0x24, 0x99,
	0x85, 0x59, 0xab, 0xce, 0x45, 0x19, 0x56, 0x9e, 0xdf, 0xa3, 0xee, 0x33, 0x4e, 0xce, 0x8a, 0x9b,
	0xc8, 0x3c, 0x88, 0x0e, 0x15, 0xd6, 0xae, 0x66, 0xed, 0x6e, 0x5b, 0xeb, 0x33, 0xe9, 0x19, 0x8e,
	0x65, 0x9b, 0xce, 0x93, 0x31, 0xc6, 0x4f, 0x9e, 0x8c, 0x39, 0x4b, 0xc8, 0x04, 0xb6, 0xd6, 0xdd,
	0xc9, 0x67, 0x86, 0x95, 0x3e, 0x5f, 0x1c, 0xa7, 0x6a, 0xab, 0x38, 0x12, 0xd5, 0x8c, 0xf3, 0x23,
	0x31, 0x07, 0x40, 0x7e, 0x24, 0xa5, 0x9e, 0xfd, 0xaa, 0xf9, 0x47, 0x63, 0x24, 0x7f, 0x5e, 0xdf,
	0x1d, 0x8b, 0xbf, 0xd7, 0x1f, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x4a, 0xe7, 0xf8, 0x00, 0xd2,
	0x0a, 0x00, 0x00,
}
